### PR TITLE
Added stop func to stop the task early. added async callbacks for Rea…

### PR DESCRIPTION
**Pull request by kenthinson**
This look ok?

### CODE REVIEW

**Comment by kareman** [comment]
```swift
/** Callback with when ReadableStream has data.*/
extension ReadableStream {
    public func onOutput ( handler: ((String) -> ())? ) {
        if let h = handler{
            filehandle.readabilityHandler = {(NSFileHandle) in
                if let output = self.readSome(){
                    h(output)
                }
            }
        }
    }
}		  
```

    I figured if you are trying to get this callback you are after the string that is currently in the buffer? Again I might be overlooking something :/

Yes in most cases this will be true. But I would still like to leave that decision to the SwiftShell users. Maybe they would like to call `readSome` several times if they don't get enough output on the first try, or to check if the end has been reached. Maybe they need to get everything at once with `read`. And in rare cases they may want to just be notified that there is some output without actually fetching the output.

**Comment by kareman** [comment]
but you can rename the method above to  onStringOutput or something like that and use that as a shortcut. I suspect most of the time people will be using that function instead of onOutput.

**Comment by kenthinson** [comment]
That's a good idea. I've got a lot of homework this week , and my mom just had spine surgery so I'm helping her around the house. so I'm not sure when I'll have time to put together another pull request.

**Comment by kareman** [comment]
No problem, I just added some indentation, unit tests and documentation and merged your commits into master. Thanks again for the great work 👍 .

**Comment by kareman** [comment]
And hope your mother gets better soon.

**Comment by kenthinson** [comment]
Thanks :)

**Pull request merged**
