### PR TITLE
Swift 3.1 Correctly Removes Task

### PR DESCRIPTION
**Pull request by Yasumoto**
Looks like this may be fallout from https://bugs.swift.org/browse/SR-3279

### CODE REVIEW

**Comment by Yasumoto** [comment]
This might need a bit more testing to make sure it works as expected (and actually fixes the issue I'm seeing). I'll be back with some better examples + tests.

**Comment by Yasumoto** [comment]
Yep, `swift test` passes on `3.0.2` and when I update to

```sh
cat ./.swift-version 
3.1-DEVELOPMENT-SNAPSHOT-2017-03-16-a
```

on Ubuntu 14.04 LTS.

**Comment by kareman** [comment]
@Yasumoto Very good. Could you try simplifying it to

 ```swift
#if !(os(macOS) || os(iOS) || os(tvOS) || os(watchOS)) && !swift(>=3.1)
typealias Process = Task
#endif
```

I think that should do the same thing.

**Comment by kareman** [comment]
Thank you very much for the fix. I will update Travis to automatically test both Swift 3.0.2 and Swift 3.1 beta from now on.

**Pull request merged**
